src/LODM.highlights/Controllers/DestinyController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LODM.highlights.Services;
using LODM.highlights.Services.Interfaces;
using LODM.highlights.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace LODM.highlights.Controllers
{
    public class DestinyController : Controller
    {
        private readonly IHighlightService _highlightService;
        private readonly IMember _memberService;
        private readonly AppSettings _appSettings;

        public DestinyController(IHighlightService highlightService, IOptions<AppSettings> appSettings, IMember memberService)
        {
            _highlightService = highlightService;
            _memberService = memberService;
            _appSettings = appSettings.Value;
        }

        [Route("/Destiny")]
        public async Task<IActionResult> Destiny(bool? disableCache)
        {
            var highlightList = new List<HighlightList>();//await _highlightService.GetOverwatchHighlightsAsync("KingxMurphy",User, disableCache ?? false);
            var allMembers = _memberService.GetAll();
            foreach (var member in allMembers)
            {
                highlightList.Add(
                    await _highlightService.GetOverwatchHighlightsAsync(member.GamerTag, User, disableCache ?? false));
            }

            return View(new DestinyViewModel
            {
                MembersList = allMembers,
                HighlightsList = highlightList
            });
        }
    }
}

src/LODM.highlights/Controllers/PlayerBioController.cs
using System.Collections.Generic;
using System.Linq;
using LODM.highlights.Models.BioViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using LODM.highlights.Services.Interfaces;

namespace LODM.highlights.Controllers
{
    public class PlayerBioController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly IMember _memberService;

        public PlayerBioController(IOptions<AppSettings> appSettings, IMember memberService)
        {
            _appSettings = appSettings.Value;
            _memberService = memberService;
        }
        // GET: /PlayerBio/PlayerBio
        [HttpGet]
        public IActionResult PlayerBio(string selectedPlayerGamerTag)
        {
            var selectedPlayer = _memberService.GetAll().FirstOrDefault(x => x.GamerTag == selectedPlayerGamerTag);
            var playerBio = getPlayerBio(selectedPlayer);
            ViewData["SelectedMember"] = selectedPlayerGamerTag;

            return View(playerBio);
        }

        private static BioViewModel getPlayerBio(Member player)
        {
            if(player == null)
                return new BioViewModel();

            return new BioViewModel
            {
                PlayerBio = player,
                GameInformationList = new List<GameInformation>
                {
                    new GameInformation
                    {
                        Title = "Overwatch",
                        Publisher = "Blizzard",
                        Genre = "FPS",
                        BackgroundUrl = "overWatchbackground.png"
                    },
                    new GameInformation
                    {
                        Title = "Destiny",
                        Publisher = "Bungie",
                        Genre = "FPS Looter Shooter",
                        BackgroundUrl = "destinyBackground.jpg"
                    },
                    new GameInformation
                    {
                        Title = "Division",
                        Publisher = "Ubisoft",
                        Genre = "3rd person Cover Shooter Travesty",
                        BackgroundUrl = "tempBackground.jpg"
                    }
                }
            };
        }
    }
}

src/LODM.highlights/Views/Shared/_EmbedHighlightPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@using LODM.highlights.ViewModels
@using Microsoft.EntityFrameworkCore.Metadata.Internal
@model HomeViewModel

<div class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <iframe id="embedFrame" class="embed-responsive embed-responsive-16by9" scr=""></iframe>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                @*<button type="button" class="btn btn-primary">Save changes</button>*@
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

src/LODM.highlights/Views/Shared/_Layout.cshtml
@using Microsoft.ApplicationInsights.Extensibility
@using Microsoft.AspNetCore.Razor.TagHelpers
@inject LODM.highlights.Services.Interfaces.IMember MemberService;

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LODM.highlights</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">
                    LODM Highlights
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Overwatch Highlights</a></li>
                    @*<li><a asp-controller="Destiny" asp-action="Destiny">Destiny Highlights(soon)</a></li>*@
                    <li><a asp-route="DestinyMappedRoute">Destiny Highlights</a></li>
                    @if (MemberService.GetAll().Any())
                    {
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="False">Players <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <member-list selected-member="@ViewData["SelectedMember"]"></member-list>
                                @*@foreach (var member in MemberService.GetAll().OrderBy(x => x.GamerTag))
                                {
                                    <li><a asp-controller="PlayerBio" asp-action="PlayerBio" asp-route-selectedPlayerGamerTag="@member.GamerTag">@member.GamerTag</a></li>
                                }*@
                            </ul>
                        </li>
                    }
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @*@await Html.PartialAsync("_LoginPartial")*@
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - KingxMurphy</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>